### ISSUE TITLE
Android build error.WritableNativeMap不是抽象的, 并且未覆盖ReadableMap中的抽象方法getDynamic(String)

### ISSUE THREAD

**Issue by Lxxyx** [anysome/react-native-pure-notification#2]
![image](https://cloud.githubusercontent.com/assets/13161470/24534178/d390d46a-15fe-11e7-999f-1cd815b546aa.png)

系统：MacOS 10.12
Node: v7.7.4
react-native: 0.42.3

做了什么：
按照教程引入，尝试打包，出错。

**Comment by iNeedToCopy** [comment]
同样的问题，怎么解决的呢？

**Comment by ghost** [comment]
change line 
       line 188: WritableMap inboxStyle = new WritableNativeMap();
to 
       line 188: WritableMap inboxStyle = new com.facebook.react.bridge.WritableNativeMap();
